telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
    username: p3_currency_telegram_bot
    token: 6841633842:AAG7RMflgByFe89tDwbfA8MnJAluSPOULLg
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

config:
  min-time: 10
  refresh-time: "0 0/2 * * * ?"