telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
    username: botUsername
    token: bot token

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

config:
  notify:
    value: 10
    unit: MINUTES
  refresh-time: "0 0/2 * * * ?"